---
abstract: 'Send Email from Catalyst'
author:
  - 'J. Shirley <jshirley@gmail.com>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-Email
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.7
  Class::C3: 0
  Email::MIME: 1.859
  Email::MIME::Creator: 1.455
  Email::Send: 2.185
resources:
  license: http://dev.perl.org/licenses/
version: 0.12
