---
abstract: 'Send Email from Catalyst'
author:
  - 'J. Shirley <jshirley@gmail.com>'
generated_by: 'Dist::Zilla version 1.093400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-Email
requires:
  Authen::SASL: "\"\""
  Catalyst: 5.7
  Catalyst::View::Mason: "\"\""
  Catalyst::View::TT: "\"\""
  Email::MIME: 1.859
  Email::MIME::Creator: 1.455
  Email::Sender::Simple: 0.100110
  MIME::Base64: "\"\""
  Moose: 0.93
  parent: "\"\""
version: 0.17
