---
abstract: 'Send Email from Catalyst'
author:
  - 'J. Shirley <jshirley@gmail.com>'
generated_by: 'Dist::Zilla version 1.093400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-Email
requires:
  Authen::SASL: 2.13
  Catalyst: 5.7
  Catalyst::View::Mason: 0.18
  Catalyst::View::TT: 0.31
  Email::MIME: 1.859
  Email::MIME::Creator: 1.455
  Email::Sender::Simple: 0.100110
  MIME::Base64: 3.08
  Moose: 0.93
  parent: 0.223
resources:
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-View-Email
version: 0.22
